Repository solidsgroup/alamo, pull requests merged in 2025-02, with the labels that each got.

#98 update .gitignore to exclude files created by clangd and pyenv
  .gitignore
Labels: enhancement

#99 add --comp-cmds flag to `configure` to generate `compile_commands.json`
  .clang-format
  .gitignore
  configure
Labels: enhancement

#102 Implement templated IC objects
  src/IC/BMP.H
  src/IC/Constant.H
  src/IC/Ellipse.H
  src/IC/Expression.H
  src/IC/IC.H
  src/IC/Laminate.H
  src/IC/PNG.H
  src/IC/PSRead.H
  src/IC/PerturbedInterface.H
  src/IC/Random.H
  src/IC/Sphere.H
  src/IC/TabulatedInterface.H
  src/IC/Trig.H
  src/IC/Trig2.H
  src/IC/Voronoi.H
  src/IC/Wedge.H
  src/Integrator/AllenCahn.H
  src/Integrator/Base/Mechanics.H
  src/Integrator/CahnHilliard.H
  src/Integrator/Dendrite.H
  src/Integrator/Flame.H
  src/Integrator/Fracture.H
  src/Integrator/HeatConduction.H
  src/Integrator/Mechanics.H
  src/Integrator/PhaseFieldMicrostructure.H
  src/Integrator/TopOp.H
Labels: enhancement, action-required

#105 Fixing some regression test errors
  src/IC/IC.H
  src/Integrator/Flame.cpp
  tests/SCPThermalSandwich/input
  tests/SCPThermalSandwich/test
  tests/Voronoi/input
Labels: bug

#115 Fix Documentation Deployment
  .github/workflows/coverage.yml
Labels: bug
